# Generated by Django 4.1.7 on 2023-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.CharField(max_length=10)),
                ('like', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=100)),
                ('tags', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
