# Generated by Django 4.1.7 on 2023-03-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0004_rename_userid_board_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='username',
            new_name='userID',
        ),
    ]
