# Generated by Django 4.1.7 on 2023-03-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0010_remove_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='userID',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='author',
        ),
    ]
