# Generated by Django 4.1.7 on 2023-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0011_rename_userid_board_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Board',
            new_name='board',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
