# Generated by Django 4.1.7 on 2023-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0012_rename_board_comment_board_alter_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
