# Generated by Django 4.1.7 on 2023-03-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbsnote', '0014_alter_board_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date']},
        ),
    ]
